; DO NOT EDIT. Generated by msgfmt.au3 at 2016-03-30_17:08:50
#include-once
Func gettext_au3_runtime(Const $sSourceText, Const $sLanguageCode)
    Switch $sLanguageCode
        Case "de" ; result of processing de.po
            Switch $sSourceText
                Case "Internationalized Test Application"
                    Return "Internationalisierte Test-Anwendung"
                Case "gettext_au3_language_select_ui() has returned %s%s%s."
                    Return "gettext_au3_language_select_ui() hat %s%s%s zurückgeliefert."
                Case "Gospel of John"
                    Return "Evangelium von Johannes"
                Case "Jesus loves you!"
                    Return "Jesus liebt Dich!"
                Case "See the Bible, %s, chapter %d, verse %d."
                    Return "Siehe die Bibel, %s, Kapitel %d, Vers %d."
                Case "Good bye!"
                    Return "Und Tschüss!"
            EndSwitch
        Case "en" ; result of processing en.po
            Switch $sSourceText
                Case "Internationalized Test Application"
                    Return "Internationalized Test Application"
                Case "gettext_au3_language_select_ui() has returned %s%s%s."
                    Return "gettext_au3_language_select_ui() has returned %s%s%s."
                Case "Gospel of John"
                    Return "Gospel of John"
                Case "Jesus loves you!"
                    Return "Jesus loves you!"
                Case "See the Bible, %s, chapter %d, verse %d."
                    Return "See the Bible, %s, chapter %d, verse %d."
                Case "Good bye!"
                    Return "Good bye!"
            EndSwitch
    EndSwitch
    ; if execution gets here, no lang/text pair has matched.
    Return '*' & $sSourceText ; * signifying 'translation missing'
EndFunc
Func gettext_au3_language_list()
    Return "de,Deutsch|en,English"
EndFunc
