#cs ----------------------------------------------------------------------------

	AutoIt Version: 3.3.14.2
	Author:         Martin Stut

	Script Function:
	List of language codes
	Included by gettext_au3_msgfmt.au3, not by runtime
#ce ----------------------------------------------------------------------------
#include-once
Func gettext_au3_language_name($language_code)
	Switch $language_code
		Case "af-za"
			Return "Afrikaans (South Africa)"
		Case "sq-al"
			Return "Albanian (Albania)"
		Case "am-et"
			Return "Amharic (Ethiopia)"
		Case "ar-sa"
			Return "Arabic (Saudi Arabia)"
		Case "hy-am"
			Return "Armenian (Armenia)"
		Case "as-in"
			Return "Assamese (India)"
		Case "az-latn-az"
			Return "Azerbaijan"
		Case "bn-in"
			Return "Bangla (India)"
		Case "eu-es"
			Return "Basque (Basque)"
		Case "be-by"
			Return "Belarusian"
		Case "bs-latn-ba"
			Return "Bosnian (Latin)"
		Case "bg-bg"
			Return "Bulgarian (Bulgaria)"
		Case "ca-es"
			Return "Catalan"
		Case "chr-cher-us"
			Return "Cherokee"
		Case "zh-cn"
			Return "Chinese (Simplified, China)"
		Case "zh-tw"
			Return "Chinese (Traditional, Taiwan)"
		Case "hr-hr"
			Return "Croatian (Croatia)"
		Case "cs-cz"
			Return "Czech (Czech Republic)"
		Case "da-dk"
			Return "Danish (Denmark)"
		Case "nl-nl"
			Return "Dutch (Netherlands)"
		Case "en-gb"
			Return "English (United Kingdom)"
		Case "en-us"
			Return "English (United States)"
		Case "et-ee"
			Return "Estonian (Estonia)"
		Case "fil-ph"
			Return "Filipino"
		Case "fi-fi"
			Return "Finnish (Finland)"
		Case "fr-ca"
			Return "French (Canada)"
		Case "fr-fr"
			Return "French (France)"
		Case "gl-es"
			Return "Galician"
		Case "ka-ge"
			Return "Georgian (Georgia)"
		Case "de-de"
			Return "German (Germany)"
		Case "el-gr"
			Return "Greek (Greece)"
		Case "gu-in"
			Return "Gujarati (India)"
		Case "he-il"
			Return "Hebrew (Israel)"
		Case "hi-in"
			Return "Hindi (India)"
		Case "hu-hu"
			Return "Hungarian (Hungary)"
		Case "is-is"
			Return "Icelandic (Iceland)"
		Case "id-id"
			Return "Indonesian (Indonesia)"
		Case "ga-ie"
			Return "Irish (Ireland)"
		Case "it-it"
			Return "Italian (Italy)"
		Case "ja-jp"
			Return "Japanese (Japan)"
		Case "kn-in"
			Return "Kannada (India)"
		Case "kk-kz"
			Return "Kazakh (Kazakhstan)"
		Case "km-kh"
			Return "Khmer (Cambodia)"
		Case "kok-in"
			Return "Konkani (India)"
		Case "ko-kr"
			Return "Korean (Korea)"
		Case "lo-la"
			Return "Lao (Laos)"
		Case "lv-lv"
			Return "Latvian (Latvia)"
		Case "lt-lt"
			Return "Lithuanian (Lithuania)"
		Case "lb-lu"
			Return "Luxembourgish (Luxembourg)"
		Case "mk-mk"
			Return "Macedonian (North Macedonia)"
		Case "ms-my"
			Return "Malay (Malaysia, Brunei, and Singapore)"
		Case "ml-in"
			Return "Malayalam (India)"
		Case "mt-mt"
			Return "Maltese (Malta)"
		Case "mi-nz"
			Return "Maori (New Zealand)"
		Case "mr-in"
			Return "Marathi (India)"
		Case "ne-np"
			Return "Nepali (Federal Democratic Republic of Nepal)"
		Case "nb-no"
			Return "Norwegian, Bokmål (Norway)"
		Case "nn-no"
			Return "Norwegian, Nynorsk (Norway)"
		Case "or-in"
			Return "Odia (India)"
		Case "fa-ir"
			Return "Persian"
		Case "pl-pl"
			Return "Polish (Poland)"
		Case "pt-br"
			Return "Portuguese (Brazil)"
		Case "pt-pt"
			Return "Portuguese (Portugal)"
		Case "pa-in"
			Return "Punjabi (India)"
		Case "quz-pe"
			Return "Quechua (Peru)"
		Case "ro-ro"
			Return "Romanian (Romania)"
		Case "ru-ru"
			Return "Russian (Russia)"
		Case "gd-gb"
			Return "Scottish Gaelic"
		Case "sr-cyrl-ba"
			Return "Serbian (Cyrillic, Bosnia and Herzegovina)"
		Case "sr-cyrl-rs"
			Return "Serbian (Cyrillic, Serbia)"
		Case "sr-latn-rs"
			Return "Serbian (Latin, Serbia)"
		Case "sk-sk"
			Return "Slovak (Slovakia)"
		Case "sl-si"
			Return "Slovenian (Slovenia)"
		Case "es-mx"
			Return "Spanish (Mexico)"
		Case "es-es"
			Return "Spanish (Spain)"
		Case "sv-se"
			Return "Swedish (Sweden)"
		Case "ta-in"
			Return "Tamil (India)"
		Case "tt-ru"
			Return "Tatar (Russia)"
		Case "te-in"
			Return "Telugu (India)"
		Case "th-th"
			Return "Thai (Thailand)"
		Case "tr-tr"
			Return "Turkish (Türkiye)"
		Case "uk-ua"
			Return "Ukrainian (Ukraine)"
		Case "ur-pk"
			Return "Urdu"
		Case "ug-cn"
			Return "Uyghur"
		Case "uz-latn-uz"
			Return "Uzbek (Latin)"
		Case "ca-es-valencia"
			Return "Valencian"
		Case "vi-vn"
			Return "Vietnamese"
		Case "vi-vn"
			Return "Vietnamese"
		Case "cy-gb"
			Return "Welsh (Great Britain)"
		Case Else
			Return $language_code & "-language"
	EndSwitch
EndFunc   ;==>gettext_au3_language_name
