; DO NOT EDIT. Generated by msgfmt.au3 at 2016-03-26_18:11:15
#include-once
Func gettext_au3_runtime(Const $sSourceText, Const $lang)
    Switch $lang
        Case "de" ; result of processing de.po
            Switch $sSourceText
                Case "Internationalized Test Application"
                    Return "Internationalisierte Test-Anwendung"
                Case "gettext_au3_language_select_ui() has returned %s."
                    Return "gettext_au3_language_select_ui() hat %s zurückgeliefert."
                Case "Gospel of John"
                    Return "Evangelium von Johannes"
                Case "Jesus loves you! See the Bible, %s, chapter %d, verse %d."
                    Return "Jesus liebt Dich! Siehe die Bibel, %s, Kapitel %d, Vers %d."
                Case "Good bye!"
                    Return "Und Tschüss!"
            EndSwitch
        Case "en" ; result of processing en.po
            Switch $sSourceText
                Case "Internationalized Test Application"
                    Return "Internationalized Test Application"
                Case "gettext_au3_language_select_ui() has returned %s."
                    Return "gettext_au3_language_select_ui() has returned %s."
                Case "Gospel of John"
                    Return "Gospel of John"
                Case "Jesus loves you! See the Bible, %s, chapter %d, verse %d."
                    Return "Jesus loves you! See the Bible, %s, chapter %d, verse %d."
                Case "Good bye!"
                    Return "Good bye!"
            EndSwitch
    EndSwitch
    ; if execution gets here, no lang/text pair has matched.
    Return '*' & $sSourceText ; * signifying 'translation missing'
EndFunc
