; DO NOT EDIT. Generated by gettext_au3_msgfmt.exe at 2016-04-08_14:36:51
#include-once
Func gettext_au3_runtime(Const $sSourceString, Const $sLanguageCode)
    Switch $sSourceString
        Case "Internationalized Test Application"
            Switch $sLanguageCode
                Case "de"
                    Return "Internationalisierte Test-Anwendung"
            EndSwitch ; $sLanguageCode
        Case "gettext_au3_language_select_ui() has returned %s%s%s."
            Switch $sLanguageCode
                Case "de"
                    Return "gettext_au3_language_select_ui() hat %s%s%s zurückgeliefert."
                Case "en"
                    Return "gettext_au3_language_select_ui() has returned %s%s%s."
            EndSwitch ; $sLanguageCode
        Case "Gospel of John"
            Switch $sLanguageCode
                Case "de"
                    Return "Evangelium von Johannes"
            EndSwitch ; $sLanguageCode
        Case "Jesus loves you!"
            Switch $sLanguageCode
                Case "de"
                    Return "Jesus liebt Dich!"
                Case "en"
                    Return "Jesus loves you!"
            EndSwitch ; $sLanguageCode
        Case "See the Bible, %s, chapter %d, verse %d."
            Switch $sLanguageCode
                Case "de"
                    Return "Siehe die Bibel, %s, Kapitel %d, Vers %d."
                Case "en"
                    Return "See the Bible, %s, chapter %d, verse %d."
            EndSwitch ; $sLanguageCode
        Case "Good bye!"
            Switch $sLanguageCode
                Case "de"
                    Return "Und Tschüss!"
            EndSwitch ; $sLanguageCode
    EndSwitch ; $sSourceString
    ; if execution gets here, no lang/text pair has matched.
    Return '' ; '' signifying 'translation missing'
EndFunc
Func gettext_au3_language_list()
    Return "de,Deutsch|en,English"
EndFunc
